### ISSUE TITLE
Data for Washington region feature

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/Requests#24]
Data tasks for Washington region feature. Data should be compiled into spreadsheets and formatted into charts following the guidelines Ben Chartoff provided.

- [x] Population in Washington MSA and inner region, 1970 – 2017 (line chart showing time trends; data sources: NCDB + [Census population estimates](https://www.census.gov/data/datasets/2017/demo/popest/counties-total.html))
- [x] Jobs (Employment) in Washington MSA and inner region, 1990 - 2017 (line chart showing time trends; data source: QCEW)
           -Download data- https://www.bls.gov/cew/datatoc.htm - NAICS based - all industries, CSVs by area (annual averages) - has separate CSVs for counties and metro areas.  or if look at the county high-level file. Indicator we want to look at is: Annual Average Employment
           -SAS macro available to help with read-in:  https://data.bls.gov/cew/doc/access/data_access_examples.htm#SAS
- [x] Commuting times to work by county for Washington MSA, 2000 to 2012-16 (bar chart? data source: Census + ACS)

Inner region defined as District of Columbia; Montgomery Co, Prince George’s Co; Arlington, Alexandria, Fairfax City/Co., Loudoun Co. 

Note: HFPC will do the cost burden data.

**Comment by lhendey** [comment]
@ptatian - i edited your request above. Is this the correct code to quickly apply the metro id to the county data? 
  metro15 = put( ucounty, $ctym15f );

**Comment by ptatian** [comment]
Yes, that looks right.

**Comment by ptatian** [comment]
@maggiesu0725 Here is an assignment for the work on the Washington region feature we had been discussing. Would you have time to pull these data together tomorrow? Please let me know.

**Comment by rpitingolo** [comment]
@ptatian I'm helping @maggiesu0725 get some things set up and we have a few questions.

1.  Census population estimates should she download CSVs and then read those in to SAS? Did you have something else in mind?
2. For the BLS data should all the code / data be saved in the requests library? Or elsewhere?
Thanks!

**Comment by ptatian** [comment]
@rpitingolo @maggiesu0725 This is a rush, so I don't think you necessarily have to use SAS. Whatever is must expeditious to create the exhibits we need. 

I would just do all of the work in Requests for now. If we decide later having the BLS data in a separate library would be valuable, we can always move it.

**Comment by ptatian** [comment]
@maggiesu0725 We need a couple more things to finish the data work on this piece. Would you be able to do the following tasks Monday? 

- [ ] Use 2012-16 IPUMS data to fill in _XX_ and _YY_: "Among [inner region] households with incomes below 80% of the area median, _XX_ percent of renters and _YY_ percent of owners have unaffordable cost burdens [30% of income]."

- [ ] Use 2012-16 ACS to fill in _X.X_ and _Y.Y_: "As of 2012-16, the rental vacancy rate for the inner region stands at _X.X_ percent and the vacancy rate for for-sale housing is _X.X_ percent."

Please let @lhendey or me know if you have questions. Thanks.

**Comment by rpitingolo** [comment]
@ptatian do you have a sense of how to define "inner county" via iPums? I know @maggiesu0725 was using a county list for the ACS data. The problem with iPums is that some counties are suppressed. For example I think Falls Church city gets a suppressed county code. You may need to have a PUMA based "inner county" definition to avoid accidentally dropping data. @lhendey

**Comment by lhendey** [comment]
@rpitingolo @maggiesu0725 - you should double-check but Falls Church and Fairfax city were previously part of the Fairfax County PUMAs.  Loudoun used to be combined with 4 other counties but I think it has it's own set of PUMAs now. @ptatian

**Comment by ptatian** [comment]
@rpitingolo @lhendey @maggiesu0725 Sorry, I was under the mistaken impression that we had already figured this out. How did we do the severe cost burden estimates that we have already?

**Comment by rpitingolo** [comment]
@ptatian @lhendey @maggiesu0725 maybe we have. Sorry if I missed it when I was out on Friday afternoon.

**Comment by lhendey** [comment]
@ptatian @maggiesu0725  was just using standard tabs.  i  don't think we ran anything with ipums. @rpitingolo

**Comment by ptatian** [comment]
@lhendey I couldn't find that tab. Only B25106, which has 30% or more.

**Comment by rpitingolo** [comment]
@lhendey I think we can pull a county/puma crosswalk out of the mable/corr system pretty easily. I'll check on that. @ptatian @maggiesu0725

**Comment by rpitingolo** [comment]
@maggiesu0725 here's the code that should flag the inner region from the ipums. Please run a total population to total households to check. 

`if puma in (101,102,103,104,105,1001,1002,1003,1004,1005,1006,1007,1101,1102,1103,1104,1105,1106,1107,1301,1302,10701,10702,10703,51255,59301,59302,59303,59304,59305,59306,59307,59308,59309) then innercounty = 1;`

**Comment by maggiesu0725** [comment]
"Among [inner region] households with incomes below 80% of the area median, 66 percent of renters and 66 percent of owners have unaffordable cost burdens [30% of income]."

"As of 2012-16, the rental vacancy rate for the inner region stands at 5 percent and the vacancy rate for for-sale housing is 1 percent."

@ptatian @lhendey @rpitingolo

**Comment by lhendey** [comment]
@ptatian - did you want actual 80% of AMI or HUD 80% (capped version)?

**Comment by ptatian** [comment]
@lhendey In the past we've used HUD's version. I feel like we should stick with that definition unless there's some reason to change.

**Comment by maggiesu0725** [comment]
**update**
"Among [inner region] households with incomes below 80% of the area median, 73 percent of renters and 73 percent of owners have unaffordable cost burdens [30% of income]."

"As of 2012-16, the rental vacancy rate for the inner region stands at 5 percent and the vacancy rate for for-sale housing is 1 percent."

@ptatian @lhendey @rpitingolo

**Comment by lhendey** [comment]
thanks @maggiesu0725  - for future reference please use rentgrs instead of rent to calculate burden. (i've updated the program).
