### ISSUE TITLE
Request for ACS data for DC AI from Planning/Communications

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/Requests#40]
**B19001, B19001I, B19001D, B19001B, and B19001A files for the 2013-2017 ACS 5-year estimates crosswalked to the 2000 census tracts.**

Data should be presented with cells as rows and tracts as columns, following the format in the [sample Excel file](https://urbanorg.box.com/s/oytdqumj7u5uvtzn953ahztmj0zp4aw1) that they provided.

**Comment by ptatian** [comment]
@rpitingolo Spoke with the requestor on the phone and we agreed to provide the data in a simplified format. You should try to follow the structure that they laid out in [sample Excel file](https://urbanorg.box.com/s/oytdqumj7u5uvtzn953ahztmj0zp4aw1), but you don't need to replicate it in all details. The main thing is following the row/column structure so that they can more easily copy and paste into what they need. 

When you've had a chance to review please let me know when this can be completed. Thank you.

**Comment by rpitingolo** [comment]
@ptatian OK, so I need to transpose the data from our files to fit into this format. Is it correct that you confirmed 2013-2017 ACS is the correct set of years?

**Comment by ptatian** [comment]
@rpitingolo I did note MOE was in some of the other workbooks. I can ask but please proceed as if we are just filling in the sheet that they indicated.

**Comment by ptatian** [comment]
@rpitingolo Reassigned this to me

**Comment by ptatian** [comment]
Batch submit log:
L:\Libraries\Requests\Prog\2019\Lauber_2019_02_22.log
