### ISSUE TITLE
Update DC units by gross rent trend chart to 2018

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/Requests#46]
Using **Prog\2018\Gross_rent_2005_2016.sas** as a model, write a new program to create an updated version of the units by gross rent chart for DC in **L:\Libraries\Requests\Prog\2018\Gross_rent_2005_2016 Chart.xlsx** that extends time series through 2018. 

Put new program and new workbook in **Prog\2019** folder.

**Comment by ptatian** [comment]
@rpitingolo Please assign this issue to someone.

**Comment by rpitingolo** [comment]
@maggiesu0725 can you please take a look at this issue and let me know if you have any questions about what @ptatian is looking for? I can review once it is ready. Thanks.

**Comment by maggiesu0725** [comment]
I will probably take a look next week is that OK? @rpitingolo

**Comment by ptatian** [comment]
That will be fine, @maggiesu0725. Thank you. cc: @rpitingolo

**Comment by rpitingolo** [comment]
@maggiesu0725 the code `dlm='09'x` in the infile statement is causing errors when it gets to the datalines. Try commenting it out and test to see if you can run the program without it.

**Comment by ptatian** [comment]
@maggiesu0725 @rpitingolo When can I get an update on this?

**Comment by rpitingolo** [comment]
@maggiesu0725 you finished this, right? Can you please merge the branch and close out the issue? Thanks. @ptatian

**Comment by maggiesu0725** [comment]
L:\Libraries\Requests\Prog\2018\Gross_rent_2005_2018.log

**Comment by ptatian** [comment]
@maggiesu0725 @rpitingolo Thanks for doing this but I don't see the new chart file. Did you create the new chart?
