### ISSUE TITLE
Land owned by faith-based institutions

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/Requests#50]
@lhendey @sstrochak I would like some basic data on land owned by faith-based institutions for a presentation I'm giving at an event on **Nov 7**. For DC, MoCo, Arlington, and Fairfax, I'd like to get estimates of these items, if possible. 

(1) Number of parcels and size of real property (square feet) owned by faith-based institutions.

(2a) Amount of (1) that is residentially zoned.
(2b) Amount of (1) that is nonresidentially zoned.

(3a) Amount of (2a) [or of (1), if (2a) not available] that is not built upon. [Note that by "not built upon" I do not mean just vacant lots. I also want to include portions of parcels that do not have structures on them, if we can do that.]

(3b) Amount of (2b) that is not built upon. 

(4a) Amount of (3a) where the not built upon portion of a parcel is 1,000 sq ft or greater. 
(4b) Amount of (3b) where the not built upon portion of a parcel is 1,000 sq ft or greater. 

Please let me know what you think. Thank you. 

[Corrected 4a/b spec]

**Comment by sstrochak** [comment]
@ptatian @lhendey It might be tricky to get the land that is not built upon because I am not sure the building area variable is reliable enough. With lot size, we can supplement with parcel shapefile, but not sure how easy it will be to get building footprints if they are missing or inaccurate in Black Knight.
2a and 2b are doable since we have a list of all the zones in each county that allow for residential.

**Comment by ptatian** [comment]
Thanks, @sstrochak. I do not want you to have to do a lot of work on this. If we can't estimate from existing data, then we can skip 3-4.

**Comment by ptatian** [comment]
@sstrochak As an alternative to 3-4, if you could estimate the percentage of 2a & 2b land area that is built upon for those parcels that seem to have good building area data, even if that's just a subset, that would be useful, too. @lhendey

**Comment by ptatian** [comment]
@lhendey @sstrochak Can I get an update on this, please. Thanks.

**Comment by lhendey** [comment]
@sstrochak could you remove "FALSE VACANT ABUTTING LOT (RES)" and "FALSE VACANT" for dc from the vacant set? Definition: Lot assigned to no real estate improvement value, but having part of a structure whose value is assigned to another lot.

**Comment by sstrochak** [comment]
@lhendey yep!

**Comment by rpitingolo** [comment]
@sstrochak @lhendey I see that the pull request associated with this issue was merged so I assume we can close this issue?

**Comment by ptatian** [comment]
@rpitingolo I would like to look at it so let's please keep it open for now. @sstrochak @lhendey

**Comment by ptatian** [comment]
Output: https://urbanorg.box.com/s/mnmvi3ge8lrsssnkjhbf0njhbtco2ccd
Markdown documentation: L:\Libraries\Requests\Prog\2019\church-zoning.html

@lhendey @sstrochak @rpitingolo Closing this issue. It did not seem like the SAS code was batch submitted on L:. For future, please save output files to appropriate L: or Box folder.
