### ISSUE TITLE
Export RCASD notices for 2017-2019

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/Requests#52]
Make a new program, adapted from **Prog/2017/Export_rcasd_2017_05_16.sas**, to export the 2017, 2018, and 2019 RCASD notices to CSV files. The new program should be saved in **Prog/2019**. 

Batch submit the program to create the CSV files.

**Comment by ptatian** [comment]
@rpitingolo Would you please assign someone to this request? Should be very straightforward but please let me know if you have questions. Would like it done in the next two weeks. Thank you.

**Comment by mcohenui** [comment]
L:\Libraries\Requests\Prog\2019\Export_rcasd_2019_11_13.log
L:\Libraries\Requests\Raw\2019\Data dictionary_rcasd_2019_11_13.xls
L:\Libraries\Requests\Raw\2019\Rcasd_2017.csv
L:\Libraries\Requests\Raw\2019\Rcasd_2018.csv
L:\Libraries\Requests\Raw\2019\Rcasd_2019.csv

**Comment by rpitingolo** [comment]
@ptatian tagging to make sure you saw Mychal's comment about the location of the files.

**Comment by ptatian** [comment]
Thank you, @mcohenui and @rpitingolo.
